### ISSUE TITLE
Incorrect actor update

### ISSUE THREAD

**Issue by Sushentsev** [shariqiqbal2810/maddpg-pytorch#38]
Hi Shariq,
In my opinion, your actor update isn't right. In the paper we should use _actor_ only for _actor_id_ and other actions we should use from buffer. Am I right? 
![image](https://user-images.githubusercontent.com/23018601/120924865-7b622100-c6de-11eb-8ea6-a20d830f0ce5.png)
![image](https://user-images.githubusercontent.com/23018601/120924887-9df43a00-c6de-11eb-85fa-4ddad39216e2.png)

**Comment by shariqiqbal2810** [comment]
Yes, you're correct in that the code does not match the paper exactly in this regard. I think it makes more sense to do it this way though (your policies should be learning based on the *current* behavior of the other policies, not a uniform sampling over their past policies). [This paper](https://arxiv.org/pdf/1804.09817.pdf) goes into a little more detail as to why it's a good idea to sample from the current policies rather than the replay buffer. I guess if you want an implementation that is perfectly representative of the original MADDPG, you can sample from the buffer, but in that case, I would just recommend using the official code.
